# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b60e5cf2977f9974ebfee08a837441847d30904a47493968c226163aa9ba4a10ecb2ff92f7e52e4167819508774953f512dd5688668260fcbbf88fb2685f532

test:
  secret_key_base: 1e1086c710e3cc0cbef0f15e46adc8ffe6f5a71aeefbdb5ef1bdf60d49f6b964a2036efdba00a2eafc80691b28cffbf61ff82927b690d922a39366572b5f31cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
